version: "2"

services:
  api:
    build:
      context: api
      dockerfile: ${APP_ENV}.dockerfile
    environment:
      - APP_ENV
      - MYSQL_USER
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_HOST
    working_dir: /var/www
    expose:
      - 9000
    depends_on:
      - database
    links:
      - database

  web:
    build:
      context: nginx
      dockerfile: ${APP_ENV}.dockerfile
    working_dir: /var/www
    expose:
      - 8080
    links:
      - api

  database:
    build:
      context: mysql
      dockerfile: Dockerfile
    environment:
      - MYSQL_USER
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    expose:
      - 3306
    volumes:
      - /opt/mysql.d/${APP_ENV}:/var/lib/mysql
