doctrine:
    dbal:
        host: '%env(resolve:MYSQL_HOST)%'
        user: '%env(resolve:MYSQL_USER)%'
        password: '%env(resolve:MYSQL_PASSWORD)%'
        driver: 'pdo_mysql'
        dbname: '%env(resolve:MYSQL_DATABASE)%'
        server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Object'
                prefix: 'App\Entity'
                alias: App
