nelmio_api_doc:
    documentation:
        servers:
            - url: http://localhost:%env(APP_PORT)%
              description: Local api server
        info:
            title: Course Rating API
            description: Everything about course ratings.
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
    areas:
        path_patterns:
            - ^/api(?!/doc[\.json]*$) # Accepts routes under /api except /api/doc

    models:
        names:
            - { alias: Course Edit, type: App\Entity\Course, groups: [ update ] }
            - { alias: Course, type: App\Entity\Course, groups: [ get ] }
            - { alias: Course Area, type: App\Entity\CourseArea, groups: [ get ] }
            - { alias: Course Area Edit, type: App\Entity\CourseArea, groups: [ update ] }
            - { alias: Course Technology, type: App\Entity\CourseTechnology, groups: [ get ] }
            - { alias: Course Technology Edit, type: App\Entity\CourseTechnology, groups: [ update ] }
