name: Check composer packages

on:
  push:
    branches: [ backend ]
  pull_request:
    branches: [ backend ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
    - uses: actions/checkout@v2

    - name: Copy default .env.example.test
      run: cp .env.test.example .env

    - name: Download docker images
      run: docker-compose -f docker-compose.yml -f docker-compose.testing.yml pull

    - uses: satackey/action-docker-layer-caching@v0.0.8
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true

    - name: Build services and initially validate them
      run: ./scripts/build.sh test

    - name: Run tests
      run: ./scripts/test.sh
