name: Check composer packages

on:
  push:
    branches: [ backend ]
  pull_request:
    branches: [ backend ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: api

    steps:
    - uses: actions/checkout@v2
      
    - name: Validate composer
      run: composer validate
    
    - name: Install dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

    - name: Run unit tests
      run: phpunit tests
