name: Check composer packages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
    - uses: actions/checkout@v2

    - name: Build services and initially validate them
      run: ./scripts/build.sh test

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: ./scripts/test.sh

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
