name: Check composer packages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
    - uses: actions/checkout@v2

    - name: Download docker images
      run: docker-compose -f docker-compose.yml -f docker-compose.testing.yml pull

    - uses: satackey/action-docker-layer-caching@v0.0.8
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true

    - name: Build services and initially validate them
      run: ./scripts/build.sh test

    - name: Run tests
      run: ./scripts/test.sh

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
